pipeline {
    agent any
    
    environment {
        NAMESPACE = "default"   //edit it as per your.
        DESIRED_PVC = "grafana-storage-pvc"
    }

    stages {
        
        stage('Git Clone') {

            steps {

               git branch: 'main', url: 'http://10.248.156.31:8081/root/k8s.git'

            }
        }

        stage('Deploy Configmap') {
            steps {
                dir('grafana') {
                    sh "k apply -f configmap.yaml -n $NAMESPACE"
                }
            }
        }

        stage('Create PV and PVC') {
            steps {
                dir('grafana') {
                    sh "k apply -f pvc.yaml -n $NAMESPACE"
                }
            }
        }

        stage('Deploy svc') {
            steps {
                dir('grafana') {
                    sh "k apply -f service.yaml -n $NAMESPACE"
                }
            }
        }

        stage('Deploy Deployment') {
            steps {
                dir('grafana') {
                    sh "k apply -f deployment.yaml -n $NAMESPACE"
                }
            }
        }   
    }   
    
        post {
        success {
            echo "Pipeline executed successfully"
        }
        failure {
            echo "Pipeline failed. Please investigate and take necessary actions."
        }
        }

}
