pipeline {
    agent any
    
    environment {
        NAMESPACE = "default"   //edit it as per your.
        DESIRED_PVC = "mysql-pvc"
    }

    stages {
        
        stage('Git Clone') {

            steps {

               git branch: 'main', url: 'http://10.248.156.31:8081/root/k8s.git'

            }
        }
        
        stage('Create PV and PVC') {
            steps {
                dir('mysql-php-app') {
                    sh "k apply -f volume.yaml -n $NAMESPACE"
                }
            }
        }

        stage('Deploy MySql') {
            steps {
                dir('mysql-php-app') {
                    sh "k apply -f mysql-deployment.yaml -n $NAMESPACE"
                }
            }
        }
        
        stage('Deploy PhpmyAdmin') {
            steps {
                dir('mysql-php-app') {
                    sh "k apply -f php-deployment.yaml -n $NAMESPACE"
                }
            }
        }
  
    }   
    
        post {
        success {
            echo "Pipeline executed successfully"
        }
        failure {
            echo "Pipeline failed. Please investigate and take necessary actions."
        }
        }

}
