apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgress
  template:
    metadata:
      labels:
        app: postgress
    spec:
      containers:
        - name: postgress
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5433
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
